spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bysj?characterEncoding=utf-8
    username: root
    password: wenli-mysql-admin
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: MYSQL
#    show-sql: true
  redis:
    host: 127.0.0.1
    password: wenli-redis-admin
    # 数据库索引 默认0
    database: 0
    port: 6380
server:
  port: 8080
  servlet:
    context-path: /wenli-app